### PR TITLE
Update errors.md

### PR DESCRIPTION
**Pull request by Svitlana007**

### CODE REVIEW

**Review by atherdon — APPROVED** [review]

**Comment by atherdon** [comment]
merging, please re-check our main website later to confirm that everything is working fine now

**Comment by Svitlana007** [comment]
> merging, please re-check our main website #139 later to confirm that everything is working fine now

не працює...

**Comment by atherdon** [comment]
тодi можемо подумати що робити

**Comment by Svitlana007** [comment]
> тодi можемо подумати що робити

вже працює

**Pull request merged**
