### PR TITLE
Create 2022-08-26-demand-curve-tested-tactics-for-growing-newsletters.md

### PR DESCRIPTION
**Pull request by Svitlana007**

### CODE REVIEW

**Comment by atherdon** [comment]
Screenshot_2022-08-27-17-52-04-086_com android chrome

**Comment by atherdon** [comment]
Тоже крешится

**Comment by atherdon** [comment]
I think we can't apply additional `:` into title variable of our articles.

i changed it to `Reading list - Demand Curve - Tested tactics for growing newsletters`

**Comment by atherdon** [comment]
yep, works now

**Comment by Svitlana007** [comment]
> yep, works now

Але чому я не бачу цієї статті на сайті?
https://llazyemail.github.io/documentation/blog

**Comment by atherdon** [comment]
Це вона? https://llazyemail.github.io/documentation/blog/demand-curve-tested-tactics-for-growing-newsletters

**Comment by Svitlana007** [comment]
> Це вона? https://llazyemail.github.io/documentation/blog/demand-curve-tested-tactics-for-growing-newsletters

вона)

**Pull request merged**
